// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbCategoriaMedicamento")]
public partial class TbCategoriaMedicamento
{
    [Key]
    public int IdCategoriaMedicamento { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [StringLength(5000)]
    [Unicode(false)]
    public string InformacaoComplementar { get; set; }

    [InverseProperty("IdCategoriaMedicamentoNavigation")]
    public virtual ICollection<TbMedicamento> TbMedicamento { get; set; } = new List<TbMedicamento>();
}