// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbCidade")]
[Index("IdEstado", Name = "IX_tbCidade_IdEstado")]
public partial class TbCidade
{
    [Key]
    public int IdCidade { get; set; }

    public int? IdEstado { get; set; }

    [Column("nome")]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [ForeignKey("IdEstado")]
    [InverseProperty("TbCidade")]
    public virtual TbEstado IdEstadoNavigation { get; set; }

    [InverseProperty("IdCidadeNavigation")]
    public virtual ICollection<TbPaciente> TbPaciente { get; set; } = new List<TbPaciente>();

    [InverseProperty("IdCidadeNavigation")]
    public virtual ICollection<TbProfissional> TbProfissional { get; set; } = new List<TbProfissional>();
}