// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbEscalaBristol")]
public partial class TbEscalaBristol
{
    [Key]
    public int IdEscalaBristol { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    public bool? Sangue { get; set; }

    [InverseProperty("IdEscalaBristolNavigation")]
    public virtual ICollection<TbEscalaBristolPacienteConsulta> TbEscalaBristolPacienteConsulta { get; set; } = new List<TbEscalaBristolPacienteConsulta>();
}