// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbExame_X_Pacientes")]
[Index("IdExame", Name = "IX_tbExame_X_Pacientes_IdExame")]
[Index("IdPaciente", Name = "IX_tbExame_X_Pacientes_IdPaciente")]
public partial class TbExameXPacientes
{
    [Key]
    [Column("IdExame_X_Paciente")]
    public int IdExameXPaciente { get; set; }

    public int IdExame { get; set; }

    public int IdPaciente { get; set; }

    public DateOnly? Data { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string Resultado { get; set; }

    [ForeignKey("IdExame")]
    [InverseProperty("TbExameXPacientes")]
    public virtual TbExame IdExameNavigation { get; set; }

    [ForeignKey("IdPaciente")]
    [InverseProperty("TbExameXPacientes")]
    public virtual TbPaciente IdPacienteNavigation { get; set; }
}