// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbGruposReceitasDespesas")]
public partial class TbGruposReceitasDespesas
{
    [Key]
    public int IdReceitaDespesa { get; set; }

    public int Tipo { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [InverseProperty("IdReceitaDespesaNavigation")]
    public virtual ICollection<TbLancarReceitasDespesas> TbLancarReceitasDespesas { get; set; } = new List<TbLancarReceitasDespesas>();
}