// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbHistoricoDoencaAtual")]
[Index("IdPaciente", Name = "IX_tbHistoricoDoencaAtual_IdPaciente")]
[Index("IdPatologia", Name = "IX_tbHistoricoDoencaAtual_IdPatologia")]
public partial class TbHistoricoDoencaAtual
{
    [Key]
    [Column("IdHDA")]
    public int IdHda { get; set; }

    public int IdPaciente { get; set; }

    public int? IdPatologia { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string Historico { get; set; }

    public int? Cirurgia { get; set; }

    public int? Trauma { get; set; }

    public int? Infeccao { get; set; }

    public int? Neoplasia { get; set; }

    public int? Metastase { get; set; }

    public int? Queimadura { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string ObsNeoplasia { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string ObsMetastase { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string ObsQueimadura { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Outros { get; set; }

    [ForeignKey("IdPaciente")]
    [InverseProperty("TbHistoricoDoencaAtual")]
    public virtual TbPaciente IdPacienteNavigation { get; set; }

    [ForeignKey("IdPatologia")]
    [InverseProperty("TbHistoricoDoencaAtual")]
    public virtual TbPatologia IdPatologiaNavigation { get; set; }
}