// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbHoraPaciente_Profissional")]
[Index("IdPaciente", Name = "IX_tbHoraPaciente_Profissional_IdPaciente")]
[Index("IdProfissional", Name = "IX_tbHoraPaciente_Profissional_IdProfissional")]
public partial class TbHoraPacienteProfissional
{
    [Key]
    [Column("IdHoraPaciente_Profissional")]
    public int IdHoraPacienteProfissional { get; set; }

    public int IdPaciente { get; set; }

    public int IdProfissional { get; set; }

    public DateOnly? DataConsulta { get; set; }

    [Precision(0)]
    public TimeOnly HoraInicioIndividual { get; set; }

    [Precision(0)]
    public TimeOnly HoraFimIndividual { get; set; }

    public bool PrimeiraConculta { get; set; }

    public bool Compareceu { get; set; }

    [StringLength(5000)]
    [Unicode(false)]
    public string Motivo { get; set; }

    [StringLength(5000)]
    [Unicode(false)]
    public string Resumo { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Valor { get; set; }

    [ForeignKey("IdPaciente")]
    [InverseProperty("TbHoraPacienteProfissional")]
    public virtual TbPaciente IdPacienteNavigation { get; set; }

    [ForeignKey("IdProfissional")]
    [InverseProperty("TbHoraPacienteProfissional")]
    public virtual TbProfissional IdProfissionalNavigation { get; set; }

    [InverseProperty("IdHoraPacienteProfissionalNavigation")]
    public virtual ICollection<TbAntropometria> TbAntropometria { get; set; } = new List<TbAntropometria>();

    [InverseProperty("IdHoraPacienteProfissionalNavigation")]
    public virtual ICollection<TbEscalaBristolPacienteConsulta> TbEscalaBristolPacienteConsulta { get; set; } = new List<TbEscalaBristolPacienteConsulta>();

    [InverseProperty("IdHoraPacienteProfissionalNavigation")]
    public virtual ICollection<TbExameFisico> TbExameFisico { get; set; } = new List<TbExameFisico>();

    [InverseProperty("IdHoraPacienteProfissionalNavigation")]
    public virtual ICollection<TbRastreamentoMetabolico> TbRastreamentoMetabolico { get; set; } = new List<TbRastreamentoMetabolico>();
}