// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbLancarReceitasDespesas")]
[Index("IdReceitaDespesa", Name = "IX_tbLancarReceitasDespesas_IdReceitaDespesa")]
public partial class TbLancarReceitasDespesas
{
    [Key]
    public int IdLancamento { get; set; }

    public int IdReceitaDespesa { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Data { get; set; }

    [ForeignKey("IdReceitaDespesa")]
    [InverseProperty("TbLancarReceitasDespesas")]
    public virtual TbGruposReceitasDespesas IdReceitaDespesaNavigation { get; set; }
}