// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbPatologia")]
public partial class TbPatologia
{
    [Key]
    public int IdPatologia { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [StringLength(5000)]
    [Unicode(false)]
    public string InformacaoComplementar { get; set; }

    [InverseProperty("IdPatologiaNavigation")]
    public virtual ICollection<TbGrupoPatologicoXPatologia> TbGrupoPatologicoXPatologia { get; set; } = new List<TbGrupoPatologicoXPatologia>();

    [InverseProperty("IdPatologiaNavigation")]
    public virtual ICollection<TbHistoriaPatologica> TbHistoriaPatologica { get; set; } = new List<TbHistoriaPatologica>();

    [InverseProperty("IdPatologiaNavigation")]
    public virtual ICollection<TbHistoricoDoencaAtual> TbHistoricoDoencaAtual { get; set; } = new List<TbHistoricoDoencaAtual>();
}