// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbPergunta")]
[Index("IdProfissional", Name = "IX_tbPergunta_IdProfissional")]
public partial class TbPergunta
{
    [Key]
    public int IdPergunta { get; set; }

    public int IdProfissional { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string Nome { get; set; }

    public bool Ativo { get; set; }

    [ForeignKey("IdProfissional")]
    [InverseProperty("TbPergunta")]
    public virtual TbProfissional IdProfissionalNavigation { get; set; }

    [InverseProperty("IdPerguntaNavigation")]
    public virtual ICollection<TbRastreamentoResposta> TbRastreamentoResposta { get; set; } = new List<TbRastreamentoResposta>();
}