// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbRastreamentoResposta")]
[Index("IdPergunta", Name = "IX_tbRastreamentoResposta_IdPergunta")]
public partial class TbRastreamentoResposta
{
    [Key]
    public int IdRastreamentoResposta { get; set; }

    public int IdPergunta { get; set; }

    public int VlrRespota { get; set; }

    public int IdParteCorpo { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string Obs { get; set; }

    [ForeignKey("IdPergunta")]
    [InverseProperty("TbRastreamentoResposta")]
    public virtual TbPergunta IdPerguntaNavigation { get; set; }

    [InverseProperty("IdRastreamentoRespostaNavigation")]
    public virtual ICollection<TbRastreamentoMetabolico> TbRastreamentoMetabolico { get; set; } = new List<TbRastreamentoMetabolico>();
}