// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbReceitaAlimentarPadrao")]
[Index("IdProfissional", Name = "IX_tbReceitaAlimentarPadrao_IdProfissional")]
public partial class TbReceitaAlimentarPadrao
{
    [Key]
    public int IdReceitaAlimentarPadrao { get; set; }

    public int? IdProfissional { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [StringLength(5000)]
    [Unicode(false)]
    public string InformacaoComplementar { get; set; }

    [ForeignKey("IdProfissional")]
    [InverseProperty("TbReceitaAlimentarPadrao")]
    public virtual TbProfissional IdProfissionalNavigation { get; set; }

    [InverseProperty("IdReceitaAlimentarPadraoNavigation")]
    public virtual ICollection<TbReceitaAlimentarPadraoXAlimento> TbReceitaAlimentarPadraoXAlimento { get; set; } = new List<TbReceitaAlimentarPadraoXAlimento>();
}