// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbReceitaMedicaPadrao")]
[Index("IdProfissional", Name = "IX_tbReceitaMedicaPadrao_IdProfissional")]
public partial class TbReceitaMedicaPadrao
{
    [Key]
    public int IdReceitaMedicaPadrao { get; set; }

    public int IdProfissional { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    [StringLength(5000)]
    [Unicode(false)]
    public string InformacaoComplementar { get; set; }

    [ForeignKey("IdProfissional")]
    [InverseProperty("TbReceitaMedicaPadrao")]
    public virtual TbProfissional IdProfissionalNavigation { get; set; }
}