// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbTipoAcesso")]
public partial class TbTipoAcesso
{
    [Key]
    public int IdTipoAcesso { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    public bool FlagAtivo { get; set; }

    [InverseProperty("IdTipoAcessoNavigation")]
    public virtual ICollection<TbProfissional> TbProfissional { get; set; } = new List<TbProfissional>();
}