// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbTipoProfissional")]
public partial class TbTipoProfissional
{
    [Key]
    public int IdTipoProfissional { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }
}